services:
    db:
        image: postgres
        ports:
            - 5432:5432
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: testUser1
            POSTGRES_DB: testdb1
        container_name: db-test-1
        volumes:
            - ~/apps/postgres-docker-test:/var/lib/postgresql/data
            - ./data/test.csv:/docker-entrypoint-initdb.d/test.csv
            - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
